<?php
// @codingStandardsIgnoreFile
?>

<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_colspan = $block->isAddAfter() ? 2 : 1;
?>

<div class="design_theme_ua_regexp" id="grid<?= /* @escapeNotVerified */ $_htmlId ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table" id="<?= /* @escapeNotVerified */ $block->getElement()->getId() ?>">
            <thead>
                <tr>
                    <?php foreach ($block->getColumns() as $columnName => $column): ?>
                        <th><?= /* @escapeNotVerified */ $column['label'] ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody id="addRow<?= /* @escapeNotVerified */ $_htmlId ?>"></tbody>
        </table>
    </div>
    <input type="hidden" name="<?= /* @escapeNotVerified */ $block->getElement()->getName() ?>[__empty]" value="" />

    <script>
        require([
                'mage/template',
                'prototype',
                'jquery'
        ], function (mageTemplate, protype, jquery) {
        // create row creator
        window.arrayRow<?= /* @escapeNotVerified */ $_htmlId ?> = {

        // define row prototypeJS template
        template: mageTemplate(
                '<tr id="<%- _id %>">'
                    <?php foreach ($block->getColumns() as $columnName => $column): ?>
                                + '<td>'
                                        + '<?= /* @escapeNotVerified */ $block->renderCellTemplate($columnName) ?>'
                                        + '<\/td>'
                    <?php endforeach; ?>


                + '<\/tr>'
                ),
                add: function(rowData, insertAfterId) {
                // generate default template data
                var templateValues;
                // Prepare template values
                if (rowData) {
                templateValues = rowData;
                } else {
                var d = new Date();
                templateValues = {
                    <?php foreach ($block->getColumns() as $columnName => $column): ?>
                        <?= /* @escapeNotVerified */ $columnName ?>: '',
                                                'option_extra_attrs': {},
                    <?php endforeach; ?>
                _id: '_' + d.getTime() + '_' + d.getMilliseconds()
                };
                }

                // Insert new row after specified row or at the bottom
                if (insertAfterId) {
                    Element.insert($(insertAfterId), {after: this.template(templateValues)});
                } else {
                    Element.insert($('addRow<?= /* @escapeNotVerified */ $_htmlId ?>'), {bottom: this.template(templateValues)});
                }

                // Fill controls with data
                if (rowData) {
                    var rowInputElementNames = Object.keys(rowData.column_values);
                    for (var i = 0; i < rowInputElementNames.length; i++) {
                        if ($(rowInputElementNames[i])) {
                            $(rowInputElementNames[i]).setValue(rowData.column_values[rowInputElementNames[i]]);
                        }
                    }
                }

                },
        }

        // add existing rows
            <?php
            foreach ($block->getArrayRows() as $_rowId => $_row) {
                //echo 'console.log(' . $_row->toJson() . ');';
                /* @escapeNotVerified */ echo "arrayRow{$_htmlId}.add(" . $_row->toJson() . ");\n";
            }
            ?>

                    // Toggle the grid availability, if element is disabled (depending on scope)
            <?php if ($block->getElement()->getDisabled()): ?>
                        toggleValueElements({checked: true}, $('grid<?= /* @escapeNotVerified */ $_htmlId ?>').parentNode);
            <?php endif; ?>
            var tr = jquery('#grid<?= /* @escapeNotVerified */ $_htmlId; ?>').closest('tr');
            tr.find('td.label').remove();
            tr.find('td.value').prop('colspan',2);

        });
    </script>
</div>
